export default {
	SET_WEATHER: "SET_WEATHER",
	FETCH_WEATHER: "FETCH_WEATHER",
	FETCH_WEATHER_REQUEST: "FETCH_WEATHER_REQUEST",
	FETCH_WEATHER_SUCCESS: "FETCH_WEATHER_SUCCESS",
	FETCH_WEATHER_FAIL: "FETCH_WEATHER_FAIL",

	SET_CITY: "SET_CITY",
	SET_COMPLETE_RESULT_LIST: "SET_COMPLETE_RESULT_LIST",
	SET_ERROR_ON_REQUEST_CITY_LIST: "SET_ERROR_ON_REQUEST_CITY_LIST",

	ADD_CITY_TO_USER_LIST: "ADD_CITY_TO_USER_LIST"
}
