export default {
	ADD_LOCATION_TO_USER_LIST: "ADD_LOCATION_TO_USER_LIST",

	THROW_LOCATION_CREATION_ERROR: "THROW_LOCATION_CREATION_ERROR",

	FETCH_LOCATION_REQUEST: "FETCH_LOCATION_REQUEST",
	FETCH_LOCATION_SUCCESS: "FETCH_LOCATION_SUCCESS",
	FETCH_LOCATION_FAIL: "FETCH_LOCATION_FAIL"
};
