export default {
	FETCH_ALL_USERS_REQUEST: "FETCH_ALL_USERS_REQUEST",
	FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
	FETCH_ALL_USERS_FAIL: "FETCH_ALL_USERS_FAIL",

	REMOVE_USER_FAIL: "REMOVE_USER_FAIL",
	REMOVE_USER_SUCCESS: "REMOVE_USER_SUCCESS"
};
